<?php

namespace App\Traits;

trait SeederData
{
	protected $fname = [
        'Alvin:f',
        'Anthony:m',
        'Antonia:f',
        'Canny:m',
        'Lovely:m',
        'Elizabeth:f',
        'Emma Josie:f',
        'Ejie:m',
        'Francisco:m',
        'Honesto:m',
        'Horacio:m',
        'Jaime Polo:m',
        'Kimberly:f',
        'Paul James:m',
        'Peter:m',
        'Roberto:m',
        'Shun:f',
        'Wally:m',
        'Zaito:m',
        'Bertrand Son:m',
        'Jeanett:f',
        'Vada:f',
        'Cyndy:f',
        'Angela:f',
        'Cherina:f',
        'Vanetta:f',
        'Sharen:f',
        'Annis:f',
        'Regene Kya:m',
        'Regine Velasquez:f',
        'Raffy:m',
        'Luke:m',
        'Rexene:f',
        'Kame:m',
        'Lucky:m',
        'Carlene:f',
        'Joellen:f',
        'Luigi:m',
        'Nickole:f',
        'Makeda:f',
        'Loma:f',
        'Carmelia:f',
        'Darrell:m',
        'Lashawna:f',
        'Shawanda:f',
        'Demarcus:m',
        'Keva:f',
        'Estrella:f',
        'Fernande:f',
    ];

    protected $lname = [
        'Chu',
        'Curacha',
        'Duterte',
        'Fuji',
        'Go',
        'Kintanar',
        'Lim',
        'Seito',
        'Suzuki',
        'Tan',
        'Toyota',
        'Yuson',
        'Kintanar',
        'Dy',
        'Chua',
        'Tiu',
        'Sy',
        'Gothong',
        'Xi',
        'Ang',
        'Choo',
        'Labiaga',
        'Renaldo',
        'Lazaro',
        'Gilbert',
        'Jamey',
        'Warren',
        'Conrad',
        'Earle',
        'Mitch',
        'Tomas',
        'Brant',
        'Ike',
        'Stacey',
        'Teddy',
        'Von',
        'Pierre',
        'Garry',
        'Lyle',
        'Nicolas',
        'Eloy',
        'Rayford',
    ];

    protected $desc = [
        "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        "I am passionate about my work. Because I love what I do, I have a steady source of motivation that drives me to do my best. In my last job, this passion led me to challenge myself daily and learn new skills that helped me to do better work. For example, I taught myself how to use Photoshop to improve the quality of our photos and graphics. I soon became the go-to person for any design needs.",
        "私は自分の仕事に情熱を傾けています。私は自分のやることが大好きなので、頑張ろうとする動機の根源があります。私の最後の仕事で、この情熱は私が毎日自分自身に挑戦し、より良い仕事をするのに役立つ新しいスキルを学ぶことにつながりました。たとえば、Photoshopを使用して写真やグラフィックの品質を向上させる方法を学びました。私はすぐに、デザインのあらゆるニーズに頼る人になりました。",
        "I am ambitious and driven. I thrive on challenge and constantly set goals for myself, so I have something to strive toward. I’m not comfortable with settling, and I’m always looking for an opportunity to do better and achieve greatness. In my previous role, I was promoted three times in less than two years.",
        "私は野心的で、意欲的です。私はチャレンジで成功し、自分自身のために常に目標を設定しているので、努力するべきことがあります。私は落ち着かないので、より良い仕事をして素晴らしいことを成し遂げる機会を常に探しています。前職では、2年以内に3回昇進しました。",
        "I am an American inventor, developer and designer.",
        "私は日本の発明家、開発者、デザイナーです。"
    ];
}
